services:
  pomerium:
    image: pomerium/pomerium:v0.30.6
    ports:
      - 443:443
    restart: always
    environment:
      POMERIUM_ZERO_TOKEN: <INSERT_TOKEN_HERE>
      XDG_CACHE_HOME: /var/cache
    volumes:
      - pomerium-cache:/var/cache
    networks:
      main:
        aliases:
          - verify.flowing-wombat-234.pomerium.app
  verify:
    image: pomerium/verify:latest
    networks:
      main:
        aliases:
          - verify

  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

networks:
  main: {}

volumes:
  pomerium-cache:
