apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "docker-registry.fullname" . }}-config
  labels:
    {{ include "docker-registry.labels" . | nindent 4 }}
data:
  config.yml: |
    version: 0.1
    log:
      level: info
    storage:
      filesystem:
        rootdirectory: /var/lib/registry
      delete:
        enabled: true
    {{- if .Values.redis.enabled }}
      cache:
        blobdescriptor: redis
    {{- end }}
    http:
      addr: :5000
    {{- if .Values.tls.enabled }}
      tls:
        certificate: /certs/cert.pem
        key: /certs/key.pem
    {{- end }}
    {{- if .Values.auth.enabled }}
    auth:
      htpasswd:
        realm: basic-realm
        path: /auth/htpasswd
    {{- end }}
    {{- if .Values.redis.enabled }}
    redis:
      addr: {{ include "docker-registry.fullname" . }}-redis:6379
    {{- if .Values.redis.password }}
      password: {{ .Values.redis.password }}
    {{- end }}
      db: 0
    {{- end }}
    maintenance:
      readonly:
        enabled: false # toggle for GC
      uploadpurging:
        enabled: true
        age: 168h
        interval: 24h
        dryrun: false
    {{- with .Values.extraConfig }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
