name: Chart CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "problem1/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Lint
        run: helm lint problem1

  security_scan:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: kubescape/github-action@main
        continue-on-error: true
        with:
          format: sarif
          outputFile: results

      - name: Upload Kubescape scan results to Github Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup a local image
        run: |
          docker pull alpine:latest
          docker tag alpine localhost:5000/my-alpine:latest
          docker image ls

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Setup Minikube (action)
        uses: medyagh/setup-minikube@latest
        with:
          driver: docker
          start-args: "--ports=5000:32700"

      - name: Helm install
        working-directory: problem1
        run: |
          helm install docker-registry . -f values.yaml

      - name: Test self host registry
        run: |
          sleep 30
          docker login localhost:5000 -u admin -p demo12345
          docker push localhost:5000/my-alpine:latest
